hospedagem/urls.py
from django.urls import path
from .views import Deletar, Criar, Listar, Detalhar, Editar

urlpatterns = [
    path('listar/', Listar.as_view(), name='listar_cliente'),
    path('deletar/<int:pk>/', Deletar.as_view(), name='deletar_cliente'),
    path('editar/<int:pk>/', Editar.as_view(), name='editar_cliente'),
    path('detalhar/', Detalhar.as_view(), name='detalhar_cliente.html'),
    path('criar/', Criar.as_view(), name='criar_cliente'),
]

hotel/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hospedagem/', include('hospedagem.urls')),
]

hospedagem/models.py
from django.db import models

class Cliente(models.Model):
    nome = models.CharField(max_length=100)
    cpf= models.IntegerField()
    data_entrada= models.DateField()
    data_saida= models.DateField()

class IDCliente(models.Model):
    id_cliente= models.ForeignKey(Cliente,on_delete=models.CASCADE)

hospedagem/forms.py
# hospedagem/forms.py

from django import forms
from .models import Cliente, IDCliente

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nome', 'cpf', 'data_entrada', 'data_saida']
        # Poderia adicionar widgets personalizados, labels, help_texts etc., se necessário

class IDClienteForm(forms.ModelForm):
    class Meta:
        model = IDCliente
        fields = ['id_cliente']
        # Adicione outros campos conforme necessário

hospedagem/views.py
from django.shortcuts import render
from django.views.generic import DetailView, UpdateView, ListView, DeleteView, CreateView
from hospedagem.models import Cliente
from .forms import ClienteForm, IDClienteForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import UserPassesTestMixin

class Detalhar(DetailView):
    model = Cliente
    template_name = 'listar_cliente.html'


class Listar(ListView):
    model = Cliente
    template_name = 'listar_clientes.html'
    context_object_name = 'clientes'

    
    

    
class Editar(UserPassesTestMixin,UpdateView):
    model = Cliente
    form_class = ClienteForm
    template_name = 'editar_cliente.html'
    
    def test_func(self):
        return self.request.user.is_superuser
    


class Deletar(DeleteView):
    model = Cliente
    template_name = 'deletar_template.html'
    success_url = reverse_lazy('listar_cliente') 


class Criar(CreateView):
    model = Cliente
    template_name = 'criar_cliente.html'
    form_class = ClienteForm

def test_func(self):
        return self.request.user.is_superuser






# Create your views here.

hospedagem/templates/criar_cliente.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Criar Cliente</title>
</head>
<body>
    
    <h1>Criar Cliente</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Criar Cliente</button>
    </form>


</body>
</html>

hospedagem/templates/editar_cliente.html
<h1>Adicionar Produto</h1>
<form method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_nome">Nome:</label>
        {{ form.nome }}
    </div>
    <div class="form-group">
        <label for="id_cpf">Descrição:</label>
        {{ form.cpf }}
    </div>
    <div class="form-group">
        <label for="id_data_entrada">Preço:</label>
        {{ form.data_entrada }}
    </div>

    <div class="form-group">
        <label for="id_data_saida">Preço:</label>
        {{ form.data_saida }}
    </div>

    <button type="submit" class="btn btn-primary">Salvar</button>
</form>

hospedagem/templates/listar_clientes.html
<!-- listar_clientes.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Listar Clientes</title>
</head>
<body>
    <h1>Listar Clientes</h1>
    
    <ul>
        {% for cliente in clientes %}
            <li>{{ cliente.nome }}</li>
            <li>{{ cliente.cpf }}</li>
            <li>{{ cliente.data_entrada }}</li>
            <li>{{ cliente.data_saida }}</li>

            <h2>Editar Cliente</h2>
            <a href="{% url 'editar_cliente' pk=cliente.pk %}"><button type="button">Editar</button></a>
            
            
            <h2>Deletar Cliente</h2>
            <form method="post" action="{% url 'deletar_cliente' pk=cliente.pk %}">
                {% csrf_token %}
                <button type="submit" onclick="return confirm('Tem certeza que deseja deletar o cliente?')">Deletar</button>
            </form>

       

                

        
        {% endfor %}
    </ul>
</body>
</html>